version: '3.9'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: goqueue
    ports:
      - "5432:5432"
    command: postgres -c max_connections=1000 -c synchronous_commit=off
    # NEW: This saves your data on your local machine so it isn't deleted!
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

# Declare the named volume at the bottom
volumes:
  postgres_data: